version: '3'

services:
  apache:
    container_name: ti2_webserver
    build: ./web
    restart: unless-stopped
    environment:
      DB_ADDR: database #DB container name
      DB_PASSWORD: root #DB container root password
    ports:
      - "8080:80" #Web port
    expose:
      - 3306
    networks:
      - db_network
  db:
    container_name: database
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    expose:
      - 3306
    networks:
      - db_network
    volumes:
      - "./sql/init.sql:/docker-entrypoint-initdb.d/init.sql"
      #- "db_data:/var/lib/mysql"

networks:
  db_network:
    driver: bridge

#volumes:
#  db_data: