version: '3'

services:
  apache:
    container_name: ti2_webserver
    build: ./web
    restart: unless-stopped
    ports:
      - "8080:80" #Web port
      - "3306:3306" #SQL port for queries
  db:
    container_name: database
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - "./sql/init.sql:docker-entrypoint-initdb.d/init.sql"